services:
  - type: web
    name: telegram-file-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_API_ID
        sync: false  
      - key: TELEGRAM_API_HASH
        sync: false
      - key: GOOGLE_DRIVE_CREDENTIALS
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: WEBHOOK_URL
        value: https://telegram-file-bot.onrender.com/webhook
      - key: MAX_FILE_SIZE
        value: "52428800"
      - key: TEMP_STORAGE_PATH
        value: "./temp_files"
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /health
    autoDeploy: false